import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Şule | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav/>

      
    </div>
  )
}
